web:
  build: .
  working_dir: /data
  command: python cadastro.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5000"

db:
  image: mysql
  environment:
      MYSQL_ROOT_PASSWORD: pass02345
      MYSQL_DATABASE: ac3_fmk
  ports:
    - "3306:3306"